# Generated by Django 5.2 on 2025-04-25 08:03

import catalog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('image_file', models.ImageField(height_field='image_height', upload_to=catalog_app.models.image_upload_path, width_field='image_width')),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('caption', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_format', models.CharField(editable=False, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
