# Generated by Django 5.2 on 2025-04-25 08:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fiat', models.BooleanField(default=False)),
                ('decimals', models.PositiveSmallIntegerField(default=8)),
                ('is_stable_coin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='FuturesPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('leverage', models.PositiveSmallIntegerField(default=1)),
                ('liquidation_price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('liquidated', 'Liquidated')], default='open', max_length=10)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('margin', models.DecimalField(decimal_places=8, max_digits=30)),
                ('initial_margin', models.DecimalField(decimal_places=8, max_digits=30)),
                ('maintenance_margin', models.DecimalField(decimal_places=8, max_digits=30)),
                ('mark_price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('funding_rate', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('last_funding_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_futures_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'futures_position',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('realized_pnl', models.DecimalField(decimal_places=8, max_digits=30)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=30)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidations', to='market_app.futuresposition')),
            ],
            options={
                'db_table': 'liquidation',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('market_type', models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures')], default='spot', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('price_precision', models.PositiveSmallIntegerField(default=2)),
                ('amount_precision', models.PositiveSmallIntegerField(default=6)),
                ('min_order_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('min_notional', models.DecimalField(decimal_places=8, default=Decimal('10.0'), max_digits=20)),
                ('maker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.001'), max_digits=5)),
                ('taker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.002'), max_digits=5)),
                ('max_leverage', models.PositiveSmallIntegerField(blank=True, default=20, null=True)),
                ('funding_rate_interval', models.PositiveSmallIntegerField(blank=True, default=8, null=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_markets', to='market_app.currency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_markets', to='market_app.currency')),
            ],
            options={
                'db_table': 'market',
                'unique_together': {('base_currency', 'quote_currency', 'market_type')},
            },
        ),
        migrations.AddField(
            model_name='futuresposition',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_futures', to='market_app.market'),
        ),
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=10)),
                ('next_funding_time', models.DateTimeField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_rates', to='market_app.market')),
            ],
            options={
                'db_table': 'funding_rate',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop_limit', 'Stop Limit'), ('stop_market', 'Stop Market'), ('take_profit_limit', 'Take Profit Limit'), ('take_profit_market', 'Take Profit Market')], max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('filled_amount', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('avg_fill_price', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='open', max_length=20)),
                ('time_in_force', models.CharField(default='GTC', max_length=10)),
                ('reduce_only', models.BooleanField(default=False)),
                ('close_position', models.BooleanField(default=False)),
                ('client_order_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('fee_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market_app.currency')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market_app.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, editable=False, null=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=30)),
                ('is_maker', models.BooleanField(default=False)),
                ('fee_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market_app.currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='market_app.order')),
            ],
            options={
                'db_table': 'trade',
            },
        ),
    ]
